name: 01-basic-triggers

on:
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hi
        run:
          echo "hi"