name: 02-workflow-dispatch-triggers-with-inputs

on:
  workflow_dispatch:
    inputs:
      string-type:
        description: "Inputs"
        type: string
        required: true
        default: "latest"
      dropdown-type:
        description: 'Type of workflow to run'
        required: true
        default: 'full'
        type: choice
        options:
        - none
        - half-full
        - full
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hi
        run:
          echo "Hi. Options selected string ${{ inputs.string-type }}, dropdown ${{ inputs.dropdown-type }}"