name: 03 multiple parallel jobs

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hi
        run:
          echo "hi from job 1"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hi
        run:
          echo "hi from job 2"
  job-3:
    runs-on: ubuntu-latest
    needs: [job-1, job-2] # <<<< Notice this
    steps:
      - name: Echo hi
        run:
          echo "hi from job 3"
  job-4:
    runs-on: ubuntu-latest
    needs: job-3 # <<<<< Notice this
    steps:
      - name: Echo hi
        run:
          echo "hi from job 4"