name: 03-multiple-parallel-jobs

on:
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hi
        run:
          echo "hi from job 1"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hi
        run:
          echo "hi from job 2"
  job-3:
    runs-on: ubuntu-latest
    needs: [job-1, job-2] # <<<< Notice this
    steps:
      - name: Echo hi
        run:
          echo "hi from job 3"
  job-4:
    runs-on: ubuntu-latest
    needs: job-4 # <<<<< Notice this
    steps:
      - name: Echo hi
        run:
          echo "hi from job 4"