name: 04 passing outputs between steps

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: step-1 # id is optional. Only declare if you want to output variables from this step
        run: |
          message="Hello world"
          echo "$message"
          echo "message=$message" >> $GITHUB_OUTPUT

      - name: Step 2
        run: |
          echo "Message ${{ steps.step-1.outputs.message }}"