name: 04-passing-outputs-to-another-steps-or-jobs.yaml

on:
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: step-1
        run:
          message="Hello world"
          echo "message=$message" >> $GITHUB_OUTPUT

      - name: Step 2
        run:
          echo "Message ${{ steps.step-1.message }}"