name: 06-using-environment-variables

on:
  workflow_dispatch:

env: # This is global level environment variable. Can be used on any jobs and steps
  GLOBAL_ENV_MESSAGE: "This is from global env"

jobs:
  job-1:
    runs-on: ubuntu-latest
    outputs:
      message: ${{  steps.step-1.outputs.message }}
    steps:
      - name: Step 1
        id: step-1 # id is optional. Only declare if you want to output variables from this step
        run: |
          message="Hello world"
          echo "$message"
          echo "message=$message" >> $GITHUB_OUTPUT

      - name: Step 2
        env:
          MESSAGE_OUTPUT: ${{ steps.step-1.outputs.message }}
          EXTRA_MESSAGE: "Hi"
        run: |
          echo "Message $EXTRA_MESSAGE $MESSAGE_OUTPUT"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    env: # This is job level environment variable. Can be used in any steps within this job only
      JOB_ENV_MESSAGE: "This is from job 2 env"
    steps:
      - name: Echo messages
        env: # This is step level environment variable. Can be used within this step only.
          MESSAGE_OUTPUT: ${{ needs.job-1.outputs.message }}
          STEP_ENV_MESSAGE: "This is from step 'Echo messages' env"
        run: |
          echo "Environment variable from step level >> $STEP_ENV_MESSAGE"
          echo "Environment variable from job level >> $JOB_ENV_MESSAGE"
          echo "Environment variable from global level >> $GLOBAL_ENV_MESSAGE"