name: test windows

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Echo hi
        run: |
          echo "hi"
          echo "meows"
          mkdir meows
          dir